# SPDX-License-Identifier: GPL-3.0-or-later
# Live-session power policy for systemd-logind (Debian bookworm keys only).
# This is operating-system policy. Firmware may still sleep on lid close
# or a held power button; that is outside this file.
[Login]
NAutoVTs=1
ReserveVT=1
HandlePowerKey=ignore
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleRebootKey=ignore
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
IdleAction=ignore
IdleActionSec=infinity
