# SPDX-License-Identifier: GPL-3.0-or-later
# Refuse OS sleep. Display blanking is configured in Xorg, not here.
# systemctl poweroff remains available for the wizard Shut down action.
[Sleep]
AllowSuspend=no
AllowHibernation=no
AllowSuspendThenHibernate=no
AllowHybridSleep=no
